# Generated by Django 5.1.4 on 2024-12-22 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.option')),
                ('which_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.history')),
            ],
        ),
    ]
