# Generated by Django 5.1.4 on 2024-12-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_quiz_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_published',
        ),
    ]
